version: "3"
services:
    zm:
        image: oren47/zoneminder
        container_name: Zoneminder
        network_mode: bridge
        privileged: false
        shm_size: 16g
        environment:
           - PUID=99
           - PGID=100
           - MULTI_PORT_START=30000
           - MULTI_PORT_END=30016
           - TZ=America/New_York
           - ADVANCED_SCRIPT=1
           - INSTALL_HOOK=1
        ports:
           - "9000:9000/tcp"
           - "9443:443/tcp"
           - "8000:8000/tcp"
           - "30000:30000"
           - "30001:30001"
           - "30002:30002"
           - "30003:30003"
           - "30004:30004"
           - "30005:30005"
           - "30006:30006"
           - "30007:30007"
           - "30008:30008"
           - "30009:30009"
           - "30010:30010"
           - "30011:30011"
           - "30012:30012"
        volumes:
           - "/room/Zmd:/var/cache/zoneminder"
           - "/room/Zm:/config"
        restart: unless-stopped
